AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  EmailConfirmationFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Timeout: 30
      CodeUri: src/handler/
      Handler: index.handler
      Runtime: nodejs18.x
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MySqsQueue.Arn
            BatchSize: 10

MySqsQueue:
  Type: AWS::SQS::Queue
